image: busybox

cache:
  paths:
    - node_modules/

stages:
  - build
  - build_img
  - deploy

build_public:
  image: node
  stage: build
  script:
    - npm install hexo-cli -g
    - npm install hexo-deployer-git --save
    - npm install --save hexo-helper-live2d
    - npm install live2d-widget-model-hibiki
    - hexo generate
  artifacts:
    paths:
      - public
    expire_in: 2 days

variables: &VARIABLES
  IMAGE_PER_BRANCH_COMMIT: $CI_REGISTRY/$CI_REGISTRY_REPOSITORY/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build_img:
  image: docker
  stage: build_img
  needs:
    - job: build_public
  # only:
  #   - /^release\/.+$/
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$IMAGE_PER_BRANCH_COMMIT" -f deploy/Dockerfile .
    - docker push "$IMAGE_PER_BRANCH_COMMIT"

deploy_public:
  image: node
  stage: deploy
  only:
    - master
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install hexo-cli -g
    - npm install hexo-deployer-git --save
    - sed -i "s/TOKEN/${GITHUB_TOKEN}/g" _config.yml
    - git config --global user.email "3377939225@qq.com"
    - git config --global user.name "spring"
    - hexo deploy

deploy_img:
  image: bitnami/kubectl
  stage: deploy
  needs:
    - job: build_img
  only:
    - master
  script:
    - kubectl apply -f blog-deployment.yaml
    - kubectl apply -f blog-service.yaml
    - kubectl apply -f blog-web.yaml