image: springli/docker-node-git

cache:
  paths:
    - node_modules/

stages:
  - build
  - build_img
  - deploy

build:
  stage: build
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install hexo-cli -g
    - npm install hexo-deployer-git --save
    - npm install --save hexo-helper-live2d
    - npm install live2d-widget-model-hibiki
    - hexo generate
  artifacts:
    paths:
      - public
    expire_in: 2 days

variables: &VARIABLES
  IMAGE_PER_BRANCH_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA

build_img:
  stage: build_img
  dependencies:
    - build
  # only:
  #   - /^release\/.+$/
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

deploy:
  stage: deploy
  only:
    - master
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install hexo-cli -g
    - npm install hexo-deployer-git --save
    - sed -i "s/TOKEN/${GITHUB_TOKEN}/g" _config.yml
    - git config --global user.email "3377939225@qq.com"
    - git config --global user.name "spring"
    - hexo deploy
