image: node:12-alpine3.10

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install hexo-cli -g
    - npm install hexo-deployer-git --save
    - npm install --save hexo-helper-live2d
    - npm install live2d-widget-model-hibiki
    - hexo generate
  artifacts:
    paths:
      - /
    expire_in: 2 days

deploy:
  stage: deploy
  only:
    - master
  script:
    - ls
    - sed -i "s/TOKEN/${GITHUB_TOKEN}/g" _config.yml
    - cat _config.yml
    - hexo deploy
