apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - blog.aispring.cloud
        - www.aispring.cloud
        - "*.aispring.cloud"
        - blog_local.aispring.cloud
      secretName: aispring-https-certs
  rules:
    - host: blog.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: blog
                port: 
                  name: http
    - host: www.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: blog
                port: 
                  name: http
    - host: blog_local.aispring.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service: 
                name: blog
                port: 
                  name: http