apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: pro
  labels:
    app: blog
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: blog