apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pro
  name: blog
  labels: 
    app: blog
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: blog
  template: 
    metadata: 
      labels: 
        app: blog
    spec: 
      containers:
        - name: blog
          image: IMAGE_NAME
          imagePullPolicy: IfNotPresent
          env: 
            - name: TZ
              value: Asia/Shanghai
          ports: 
            - name: http
              containerPort: 80
          livenessProbe: 
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 180
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1